### ISSUE TITLE
Give programmatic access to the current target and the env

### ISSUE THREAD

**Issue by philc** [dmac/fezzik#10]
These are accessible as instance variables in the global scope `@environment` and `@destination`, but that's brittle. These should be methods, and possibly attached to a Fezzik class or module. See 08e6bb5 in backlot.git for a use case.

**Comment by dmac** [comment]
Related to GH-15.

**Comment by tobert** [comment]
Related: its not clear when @environment['foo'] is going to be a plain symbol or an array of [:symbol, nil] or, presumably, [:symbol, "host"].  The change over to a method should clarify this.

**Comment by cespare** [comment]
@tobert You shouldn't use `@environment` directly anymore -- you should use `@per_server_environments`. See the default generated core recipe.

This stuff is pretty janky right now -- look out for some big changes related to #15 to make the situation a lot better.
