### ISSUE TITLE
"Private" or hidden tasks

### ISSUE THREAD

**Issue by cespare** [dmac/fezzik#18]
I'm creating this ticket to track this idea that we discussed.

When we have complex deploy setups, we often end up with a large set of tasks. Most of them are not intended to be called directly, so we comment out the `desc` lines so that they don't show in `fez -T`. It would be nice to make a task (or a remote task) "private" in some way. Private tasks will be filtered out of `fez -T` and cannot be called from the `fez` commandline.

Further ideas: you can call a private task by passing some flag to fezzik. This will be useful when debugging. When you try to call a private task, you get a useful message stating that the task exists, but is private, and suggesting that you can use the flag to call it anyway.

This work should be done after we get to the main refactoring of Fezzik to make it more modular. (See issue #15.)

**Comment by dmac** [comment]
Why doesn't the solution of not including the `desc` line (or commenting it out) not work for you? That's the standard way people solve this problem with rake.

**Comment by dmac** [comment]
Closing this issue, I don't think it belongs in Fezzik.
