### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by cespare** [dmac/fezzik#20]
It would be nice to have a debug mode to print some more info. For instance, a very easy win would be to print out the name/description of each task before executing it, along with the user/domain/etc for remote tasks.

**Comment by dmac** [comment]
Another requested feature is printing out every command passed to `run` so a user can see what ssh is doing.

**Comment by dmac** [comment]
Done in b3fd8137d405642e55bd561d1a7c62cfa8bdbb6f.
