### ISSUE TITLE
Add a facility for running multiple commands over one ssh session

### ISSUE THREAD

**Issue by philc** [dmac/fezzik#25]
I'm not sure what form this should take, but if you provide a mechanism baked into fezzik and guide people to use it in the README, the deploy scripts they create will be faster and nicer.

You'll recall that we use this in Helios to get the job done.

```
# Runs all of the given commands as one big string. Each separate SSH command you run is 1s of overhead,
# so this will be much faster if one of your tasks issues many commands.
def run_commands(*commands)
  run commands.map { |command| "(#{command})" }.join(" && ")
end
```

**Comment by cespare** [comment]
#38 is a dup of this one, but it has more useful information so I'm going to close this one out.
