### ISSUE TITLE
Make fezzik work with a more advanced version of Rake

### ISSUE THREAD

**Issue by hellonoam** [dmac/fezzik#29]
At the moment fezzik is dependent on Rake 0.8.7. That version of rake has annoying bug (https://github.com/jimweirich/rake/issues/23) which has been fixed with in the new versions of Rake. 

Would be great if we could use fezzik with a more updated version of Rake.

Thanks,
Noam

**Comment by philc** [comment]
Ha, I came here to file the exact same bug about the same rake issue.

I realize we're tied to rake remote task's dependency list which locks Rake to 0.8. All the more reason to dump it.

**Comment by dmac** [comment]
Fixed in c0c9ab1f9fac6aedf305edf2cc6a5ce0ad2bca0b.
