### ISSUE TITLE
Rake complains about fezzik not including Rake::DSL

### ISSUE THREAD

**Issue by bkad** [dmac/fezzik#31]
I'm getting this error message while running rake tasks

```
Loading Fezzik tasks from config/tasks
WARNING: Global access to Rake DSL methods is deprecated.  Please include
    ...  Rake::DSL into classes and modules which use the Rake DSL methods.
WARNING: DSL method Module#import called at /Users/kle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fezzik-0.7.0/lib/fezzik/base.rb:10:in `block in init'
```

**Comment by cespare** [comment]
Are you somehow running with a recent version of rake? Fezzik requires a particular finely aged version of rake. It should pull that in, though. Are you running with bundle exec and with fezzik in your Gemfile?

**Comment by bkad** [comment]
sure enough, wasn't using bundle exec. :flushed:
