### ISSUE TITLE
Remove the rake-remote_task dependency

### ISSUE THREAD

**Issue by cespare** [dmac/fezzik#33]
The usage of rake-remote_task has been convenient so far, but has too many downsides. Here is a short list of some of the main complaints, off the top of my head:
- Tied to an old rake version (#29)
- Tends to be slow -- rake-remote_task shells out to `ssh` for every `run` command and doesn't provide functionality to execute multiple commands in sequence (also see #25)
- Clunky roles implementation (Fezzik wraps this in a nicer interface, but this shouldn't be necessary)
- Errors that come from rake-remote_task tend to be very confusing to Fezzik users
- Built-in `rsync` helper forces `--delete`

We should rewrite the core of Fezzik to not depend on rake-remote_task, but instead implement the parallel SSH functionality ourselves.

**Comment by dmac** [comment]
Weave branch merged to master, RRT dependency removed.
