### ISSUE TITLE
Provide upgrade docs

### ISSUE THREAD

**Issue by cespare** [dmac/fezzik#34]
Fezzik has undergone major backwards-incompatible changes during its history, particularly the 0.6.0 release. Understanding these changes has been a pain point for several Fezzik users. It would be good to provide documentation about the major differences between the versions and the shortest path to upgrading. A github wiki page or two would probably suffice.

It might also be worthing polling for the most popular current fez versions in use to determine which upgrade docs to provide. (This could be done by talking to people or grepping for `fezzik` in the `Gemfile.lock`s in all of the Ooyala repos.)

**Comment by dmac** [comment]
Upgrade docs for 0.8.0 written in 149c510dee3b0d3d811c16c8f4e5f7ed7a71da86.
