### ISSUE TITLE
Documentation/renaming for `remote_task`

### ISSUE THREAD

**Issue by cespare** [dmac/fezzik#35]
(Related to #32.)

It's not immediately clear from the README that `remote_task`s execute once per target host (in contrast with regular rake tasks that just execute once). Furthermore, it's totally possible to create a `remote_task` to do some per-host work **without doing any remote commands at all**. In fact, @bkad makes the point in #32 that this is actually a better way of doing something like `environment.rake`.

I suggest we standardize on `remote_task` being the usual way of doing per-host work. We should call this usage out in the documentation. Furthermore, I think we should consider wrapping or aliasing `remote_task` to give it a more suitable name, given this use case.

**Comment by dmac** [comment]
Renamed to `host_task` and documented as part of the 0.8.0 release.
