### ISSUE TITLE
Don't require default setting when using roles

### ISSUE THREAD

**Issue by dmac** [dmac/fezzik#36]
Fezzik currently requires all variables overridden with `role` to have non-role defaults. For example: the following throws an exception:

``` ruby
destination :prod do
  role :root_user, :user => "root"
end

remote_task :setup, :roles => root_user do
  run "whoami"
end

# $ fez prod setup
# undefined method `user' for Fezzik:Module
```

To avoid the exception, fezzik currently requires all overridden variables to have a default. In this example:

``` ruby
set :user, "default"
```

This should be unnecessary.

**Comment by cespare** [comment]
Ah yeah, just ran into this. `set :user, "asdfasdfa"` fixed it :unamused:

**Comment by cespare** [comment]
This is now fixed on the weave branch. The way I did it is slightly intertwined (hehe) with the weave changes so I didn't feel like making it independently and having to merge it later.

**Comment by dmac** [comment]
Nice work!
