### ISSUE TITLE
Consider adding a run_many helper

### ISSUE THREAD

**Issue by philc** [dmac/fezzik#38]
We have this in most of our deploy files, so it's probably worth moving in to the core.

Either having run itself accept vargs, or defining a run_many(...). Here's the helper method we copy and paste into many of our deploy scripts:

```
# Run multiple commands in one big ssh invocation, for brevity and ssh efficiency.
def run_commands(*commands) run commands.join(" && ") end

run_commands("cd #{release_path}",
    "bundle exec #{foreman_command}",
    "sudo rm /etc/init/#{app}*.conf || true",
    "sudo mv upstart_scripts/* /etc/init",
    "rm -R upstart_scripts")
```

**Comment by dmac** [comment]
Yep, this would be useful to have. I'd merge a pull request if you have one.

**Comment by philc** [comment]
Ah, the art of delegation. Some mentor has trained you well ;-)

**Comment by philc** [comment]
Do you have a recommended file and class to stick this on? It looks as if it should be a monkey-patched method on Rake RemoteTask.

**Comment by dmac** [comment]
That would work; we could also put it in Fezzik::Utils, same place as capture_output, etc. That way it gets properly namespaced and not dumped into the top level unless the user explicitly asks for it.

**Comment by cespare** [comment]
This change will be obviated by the replacement of rake remote-task with [Weave](https://github.com/cespare/weave), which reuses ssh connections so that sequential `run` commands are fast. I know I've been promising this for a while, but it's actually happening now (like within the next week). So, I think we shouldn't implement this in Fezzik core.

**Comment by philc** [comment]
Whaaaat this is the first I've heard of this... can't wait! Kill it!

**Comment by philc** [comment]
How's it progressing?

**Comment by dmac** [comment]
Weave is done, and @cespare and I have been working on reimplementing remote-task in some after-hours minihackathons. You can check out the weave branch to track progress.

**Comment by philc** [comment]
Seems like it stalled. Is there a list of weave-related tasks posted anywhere?

**Comment by dmac** [comment]
Weave has been merged to master, all ssh connection now use a shared pool by default.

**Comment by philc** [comment]
Awesome. Note that weave solves only the ssh efficiency aspect of run_many. I think a series of run statements without parens is brief enough, but we'll still probably use a run_many helper in many of our projects because we often cd into a directory to change the state of the session, and then run some commands.

Maybe a directory scoping block would be better than using cd and ampersands.

```
within_directory(...) do
  run "rm xyz"
  run "bundle exec foreman export..."
 end
```

**Comment by cespare** [comment]
I'm opposed to adding a `run_many` helper as described in the original issue post. This is error prone, and to do it correctly involves parsing shell code. Also I've come to regard extensive shell code in deploys as a bad smell, and I generally prefer to solve problems in ways that avoid them. Even shipping over a bash script file and running it seems better to me, in that this keeps the madness contained and separated from the Ruby deploy code, and also allows for `set -e`.

OTOH, I think I'm OK with the `within_directory` helper. The `cd ... &&` paradigm seems mostly unavoidable, so it would be nice to cut down on that noise a bit. I think this needs to go in Weave; issue filed over at cespare/weave#2.
