### ISSUE TITLE
Allow packaging of shared tasks as gems

### ISSUE THREAD

**Issue by irabinovitch** [dmac/fezzik#39]
We seem to have a lot of projects sharing the same or similar tasks.  We should kake sharing of recipes easier by allowing them to be packaged as gems.

**Comment by dmac** [comment]
This is already trivially possible. You can create a new gem that looks something like this:

``` ruby
require "rake"

namespace :fezzik do
  task :ping do
    puts "pong"
  end
end
```

Then just require the gem in your project's Rakefile and it'll be picked up automatically.
