### ISSUE TITLE
Don't use deprecated syntax in README

### ISSUE THREAD

**Issue by philc** [dmac/fezzik#48]
Update readme to use Fezzik.get :app and Fezzik.get :deploy_to instead of app, deploy_to. These issue deprecation warnings in fezzik 0.8.

From the readme:

```
Fezzik.set :deploy_to, "/opt/#{app}"
Fezzik.set :release_path, "#{deploy_to}/releases/#{Time.now.strftime("%Y%m%d%H%M")}"
Fezzik.set :current_path, "#{deploy_to}/current"
```

**Comment by dmac** [comment]
Thanks, nice catch.
